name: CI Build and Deploy Development for Hage

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hage:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/hage:latest

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker stop hage
            sudo docker rm hage
            sudo docker rmi tryhage/hage:latest
            sudo docker pull tryhage/hage:latest
            sudo docker run -d -p 3000:3000 --name hage ${{ secrets.DOCKER_USERNAME }}/hage:latest

       

       # Notify Slack on success
      - name: Slack Notification on Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: development
          text: "✅ Workflow Succeeded: ${{ github.workflow }} on branch ${{ github.ref }} by ${{ github.actor }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # Notify Slack on failure
      - name: Slack Notification on Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: development
          text: "❌ Workflow Failed: ${{ github.workflow }} on branch ${{ github.ref }} by ${{ github.actor }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

